os: linux
language: python
python: "3.7"
dist: xenial
compiler: gcc
install:
  - pip install conan
  - conan user
script:
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan install . --build=missing
  - source activate_run.sh
  - which qmake
  - qmake -v
  - qmake conan-qt-example.pro
  - make
  - ./conan-qt-example
