matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
language: python
python: "3.7"
compiler: clang
install:
  - pip install conan
  - conan user
script:
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan install . --build=missing
  - source activate.sh
  - PATH=$CMAKE_PREFIX_PATH/bin:$PATH
  - which qmake
  - qmake -v
  - qmake conan-qt-example.pro
  - make
  - ./conan-qt-example
