language: python
python: "2.7"
compiler: clang
matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
install:
  - pip install conan
script:
  - conan user
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan install . --build=missing
  - source activate_run.sh
  - which qmake
  - qmake -v
  - qmake conan-qt-example.pro
  - make
  - ./conan-qt-example
