compiler: clang
matrix:
  include:
    - os: linux
      dist: xenial
      language: python
      python: "3.6"
      install:
        - pip install conan
    - os: osx
      install:
        - brew install conan
script:
  - conan user
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan install . --build=missing
  - source activate.sh
  - PATH=$CMAKE_PREFIX_PATH/bin:$PATH
  - which qmake
  - qmake -v
  - qmake conan-qt-example.pro
  - make
  - ./conan-qt-example
