language: cpp
compiler: clang
matrix:
  include:
    - os: linux
      dist: xenial
      language: python
      python: "3.7"
      before_install:
        - pip install conan
      before_script:
        - source activate.sh
        - PATH=$CMAKE_PREFIX_PATH/bin:$PATH
    - os: osx
      before_install:
        - brew install conan
      before_script:
        - source activate.sh
        - PATH=$CMAKE_PREFIX_PATH/bin:$PATH
    - os: windows
      before_install:
        - choco install python3 pip3
        - pip3 install conan
      before_script:
        - activate.bat
install:
  - conan user
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan install . --build=missing
script:
  - qmake -v
  - qmake conan-qt-example.pro
  - make
  - ./conan-qt-example
